---
version: "2"
services:
  php:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
    - db
    environment:
    - DB_ENV_MYSQL_ROOT_PASSWORD=magento_root
    volumes:
    - ./mount/web:/var/www/html
  db:
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    image: percona:5.7
    environment:
      MYSQL_USER: magento_test
      MYSQL_DATABASE: magento_test
      MYSQL_PASSWORD: magento_test
      #mysql -hdb -umagento_test -pmagento_test
      MYSQL_ROOT_PASSWORD: magento_root
    volumes:
    - .././build/data/mysql:/var/lib/mysql